age = int(input("Please tell me your age : "))
num = int(age)
print(f"In 10 years, you'll be {num+10} years old.")
print(f"In 20 years, you'll be {num+20} years old.")
print(f"In 30 years, you'll be {num+30} years old.")