first = int(input("Give me the first number : "))
secord = int(input("Give me the second number : "))
int_first = int(first)
int_secord = int(secord)
print("Thank you!")
print(f"{int_first} + {int_secord} = {int_first+int_secord}")
print(f"{int_first} - {int_secord} = {int_first-int_secord}")
print(f"{int_first} * {int_secord} = {int_first*int_secord}")
print(f"{int_first} / {int_secord} = {int_first/int_secord}")